vp0:
  environment:
    - OPENCHAIN_PEER_VALIDATOR_CONSENSUS=obcpbft
    - OPENCHAIN_OBCPBFT_GENERAL_MODE=batch
    - OPENCHAIN_OBCPBFT_GENERAL_TIMEOUT_REQUEST=10s

vp1:
  environment:
    - OPENCHAIN_PEER_VALIDATOR_CONSENSUS=obcpbft
    - OPENCHAIN_OBCPBFT_GENERAL_MODE=batch
    - OPENCHAIN_OBCPBFT_GENERAL_TIMEOUT_REQUEST=10s

vp2:
  environment:
    - OPENCHAIN_PEER_VALIDATOR_CONSENSUS=obcpbft
    - OPENCHAIN_OBCPBFT_GENERAL_MODE=batch
    - OPENCHAIN_OBCPBFT_GENERAL_TIMEOUT_REQUEST=10s

vp3:
  environment:
    - OPENCHAIN_PEER_VALIDATOR_CONSENSUS=obcpbft
    - OPENCHAIN_OBCPBFT_GENERAL_MODE=batch
    - OPENCHAIN_OBCPBFT_GENERAL_TIMEOUT_REQUEST=10s
