vp0:
  extends:
    file: compose-defaults.yml
    service: vp
  environment:
    - OPENCHAIN_PEER_ID=vp0
    - OPENCHAIN_PEER_VALIDATOR_CONSENSUS=obcpbft
    - OPENCHAIN_PEER_VALIDATOR_REPLICAS_IPS=vp0:30303 vp1:30303 vp2:30303 vp3:30303

vp1:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp1
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
  links:
    - vp0

vp2:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp2
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
  links:
    - vp0

vp3:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp3
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
  links:
    - vp0
