vp0:
  extends:
    file: compose-defaults.yml
    service: vp
  environment:
    - OPENCHAIN_PEER_ID=vp0
    - OPENCHAIN_PEER_TLS_ENABLED=true
    - OPENCHAIN_PEER_TLS_SERVER-HOST-OVERRIDE=OBC
    - OPENCHAIN_PEER_TLS_CERT_FILE=./openchain/peer/bddtests/tlsca.cert
    - OPENCHAIN_PEER_TLS_KEY_FILE=./openchain/peer/bddtests/tlsca.priv

vp1:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp1
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
  links:
    - vp0

