vpBase:
  extends:
    file: compose-defaults.yml
    service: vp
  environment:
    - OPENCHAIN_SECURITY_ENABLED=true
    - OPENCHAIN_PEER_PKI_ECA_PADDR=obcca0:50051
    - OPENCHAIN_PEER_PKI_TCA_PADDR=obcca0:50051
    - OPENCHAIN_PEER_PKI_TLSCA_PADDR=obcca0:50051
    - OPENCHAIN_PEER_PKI_TLS_ROOTCERT_FILE=./openchain/peer/bddtests/tlsca.cert
    # TODO: Currently required due to issue reading obbca configuration location
    - OPENCHAIN_OBCPBFT_GENERAL_N=4
    # The checkpoint interval in sequence numbers
    - OPENCHAIN_OBCPBFT_GENERAL_K=2

vpSieve:
  extends:
    service: vpBase
  environment:
    - OPENCHAIN_PEER_VALIDATOR_CONSENSUS=obcpbft
    - OPENCHAIN_OBCPBFT_GENERAL_TIMEOUT_REQUEST=10s
    - OPENCHAIN_OBCPBFT_GENERAL_MODE=sieve

vpClassic:
  extends:
    service: vpBase
  environment:
    - OPENCHAIN_PEER_VALIDATOR_CONSENSUS=obcpbft
    - OPENCHAIN_OBCPBFT_GENERAL_TIMEOUT_REQUEST=10s
    - OPENCHAIN_OBCPBFT_GENERAL_MODE=classic

vpBatch:
  extends:
    service: vpBase
  environment:
    - OPENCHAIN_PEER_VALIDATOR_CONSENSUS=obcpbft
    - OPENCHAIN_OBCPBFT_GENERAL_TIMEOUT_REQUEST=10s
    - OPENCHAIN_OBCPBFT_GENERAL_MODE=batch
    # TODO: This is used for testing as to assure deployment goes through to block
    - OPENCHAIN_OBCPBFT_GENERAL_BATCHSIZE=1
