vp0:
  extends:
    file: compose-defaults.yml
    service: vp
  environment:
    - OPENCHAIN_PEER_ID=vp0

vp1:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp1
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
  links:
    - vp0

vp2:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp2
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
  links:
    - vp0
